name: C/C++ CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update PGP key
      run: curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    - name: add universe/multiverse
      run: |
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
    - name: update apt
      run: sudo apt-get update
    - name: determine check version
      run: apt policy check
    - name: executable infos
      run: (file Tests/Checks.x; file Sampling/Program.x; file Extraction/Program.x) | tr "\n" "\n"
    - name: make tests
      run: (cd Blatt01.Herrmann.Labatz.Noack && cd Aufgabe1 && HelloSimple  && make && make test)
