name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make test

 macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install check
      run: brew install check
    - name: make tests
      run: (make)
    - name: run tests
      run: (make test)
